@startuml 包图
skinparam classAttributeFontName Consolas

class 支付模块 {
}
class 订单模块 {
}
class 购物车模块 {
}
class 用户管理模块 {
}
class 留言模块 {
}
class 菜品管理模块 {
}
class 公有函数 {
}

订单模块 -- 支付模块 : 引用 >
订单模块 -- 菜品管理模块 : 引用 >
订单模块 -- 购物车模块 : 引用 >

支付模块 -- 公有函数
订单模块 -- 公有函数
购物车模块 -- 公有函数
用户管理模块 -- 公有函数
留言模块 -- 公有函数
菜品管理模块 -- 公有函数

公有函数 -- DB

@enduml
