@startuml 状态图
[*] -down-> 订单待支付: 用户点击下单
state 订单待支付{
    [*] -left-> 支付单待支付: 服务端发送创建支付单请求
    支付单待支付 -down-> 支付单已支付: 客户支付
} 
state 支付单已支付{

}
支付单已支付 -> 订单已支付
订单已支付 -down-> 订单待配送
state 订单待配送{
    [*] -> 订单待烹饪
    订单待烹饪 -> 订单已烹饪: 店家烹饪
} 

订单已烹饪 -down-> 订单配送完成: 骑手配送
订单配送完成 -left-> 订单待评价
订单待评价 -left-> 订单已评价: 用户评价
@enduml
